listeners.tcp.default = 5672
management.tcp.port = 15672
prometheus.tcp.port = 15692

loopback_users.guest = false
consumer_timeout = 1800000
disk_free_limit.absolute = 2GB
vm_memory_high_watermark.relative = 0.6

heartbeat = 60
channel_max = 2048
